# Generated by Django 2.0.5 on 2018-07-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='template',
            field=models.CharField(default='basic', max_length=10),
        ),
    ]
