# Generated by Django 2.0.5 on 2018-07-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_request', '0002_entry_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='vid_url',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
